### ISSUE TITLE
hope to use the query language as effortlessly as obsidian does

### ISSUE THREAD

**Issue by like1river2east** [karstenpedersen/obsidian-advanced-random-note#5]
Hi there! It seems the query language (Query type: Default) is not the same as obsidian search.
eg. should use `path: XXX`, not `path:XXX`, and it don't allow any space in the XXX. also don't allow any "" in the XXX
eg. seems that "Disabled folders" don't allow any space in it, and also it won't work with many folders (I use ENTER to separate the folders)
eg. seems that `path: XXX tag: XXX` won’t work
which made the plugin difficult to use.

**Comment by karstenpedersen** [comment]
Hi, I'm aware of this, but I found it kind of hard to remake their system entirely. I can look into it, but for now I recommend using regular expressions or Dataview as these are way better.

**Comment by like1river2east** [comment]
Thanks for the reply. I'll try the other two query types.
