### ISSUE TITLE
Plugin stopped working with images

### ISSUE THREAD

**Issue by saif-ellafi** [karstenpedersen/obsidian-advanced-random-note#7]
I believe this used to work but after an update it just opens blank note files now.
I was using this to pull random cards in .jpg in a folder.

As a bonus request: Would it be possible to have a context menu in a folder, to do right-click -> pick random note, and just have a random note popup as a floating window?

Thank you for working on this

**Comment by karstenpedersen** [comment]
Hi, I'm sorry about that. I will look into it today and test the update
properly this time. Can probably get it out by tomorrow.

Karsten

**Comment by karstenpedersen** [comment]
Hi, sorry for the late fix.

I should have fixed the problem now, so you should be able to open images and other file types again.

Your ideas are also great, so I will look into adding it :)

Karsten
